# Generated by Django 4.0.5 on 2022-07-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modify_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE'),
        ),
    ]
